---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - skip-changelog
    ignore:
      - dependency-name: "codecov/codecov-action"
        versions: ["4.6.0"]
